
services:
  consul:
    image: hashicorp/consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Secret123@
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  authentication:
    build:
      context: backend/services/authentication
      dockerfile: Dockerfile
    image: authentication-service:latest
    container_name: auth-service
    depends_on:
      - postgres
      - consul
    ports:
      - "8080:8080"
    env_file:
      - ./backend/services/authentication/.env
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
