services:
  api-gateway:
    build:
      context: backend/apigateway
      dockerfile: Dockerfile
  authentication:
    build:
      context: backend/services/authentication
      dockerfile: Dockerfile
    image: authentication-service:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/services/authentication/.env

