name: auth

on:
  push:
    branches: ["main"]
    paths:
      - 'backend/services/authentication/**'
  workflow_dispatch:

jobs:
  building:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        run: go build ./...

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username:  ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Setting Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setting up the docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Pushing to the Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags:  ${{vars.DOCKERHUB_USERNAME}}/auth-service:latest

