# Author: Swan Htet  Aung Phyo
name: feature.auth.yml
on:
  push:
    branches: ["feature/authentication"]
  workflow_dispatch:

jobs:
  authentication-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses:  actions/checkout@v4

      - name: Setting Up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Running the makefile
        run: cd backend/services/authentication && make dev-all



